<a href="https://colab.research.google.com/github/wheemin-2/24-2-ESAA/blob/main/0923_HW_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **사이킷런(Scikit-learn)**

In [1]:
import sklearn
print(sklearn.__version__)

1.5.2


## **붓꽃 품종 예측하기**

iris 데이터 셋으로 품종을 분류(Classification) 해보기


**분류(Classification)**

* 대표적인 지도학습(Supervised Learning) 방법 중 하나
* 학습을 위한 다양한 feature와 분류 결정값인 레이블(Lable) 데이터로 모델을 학습한 뒤, test dataset에서 미지의 레이블을 예측
* train data 학습 후 test data 예측

### **1. 데이터 불러오기**

In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

iris = load_iris()
iris_data = iris.data        # feature의 값
iris_label = iris.target     # target(setosa, vesicolor, virginica)의 인덱스 : 0,1,2
print('iris target값:', iris_label)
print('iris target명:',iris.target_names)   # target의 이름 : setosa, vesicolor, virginica

iris_df =  pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

### **2. train data, test data 분리**



```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= , random_state= )
```

* X : feature, y : Label (붓꽃의 특징(feature, X)을 통해 품종(Label, y)을 예측)
* test_size : 전체 데이터 셋 중 테스트데이터 셋의 비율 (e.g. test_size=0.2)
* random_state : 호출할 때마다 같은 학습/테스트 용 데이터 셋을 생성하기 위해 주어지는 난수 발생 값
    * seed와 같은 의미, 숫자는 상관없음
    * random_state를 지정하지 않으면 수행할 때마다 다른 학습/테스트 용 데이터를 만들 수 있음


In [4]:
# train data, test data split
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

### **3. 의사 결정 트리를 이용해 학습과 예측 수행 - DecisionTreeClassifier**


In [5]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [6]:
# 학습이 완료된 dt_clf 객체에서 테스트 데이터 셋으로 예측 수행
pred = dt_clf.predict(X_test)

### **4. 예측 성능 평가**

In [7]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


## **사이킷런의 기반 프레임워크 익히기**

### **Estimator 이해 및 fit(), predict() 메서드**

### **사이킷런의 주요 모듈**

### **내장된 예제 데이터 세트**

* 사이킷런에 내장된 데이터 세트는 일반적으로 딕셔너리 형태로 되어있음

* key : 보통 data, target, target_name, feature_names, DESCR로 구성
    * data : feature의 데이터 세트, ndarray 타입
    * target : 분류 시 레이블 값 (회귀일 때는 숫자 결과값 데이터 세트), ndarray 타입
    * target_name : 개별 레이블의 이름, ndarray 혹은 list 타입
    * feature_names : 피처의 이름, ndarray 혹은 list
    * DESCR : 데이터 세트에 대한 설명 및 각 피처의 설명, str 타입

In [9]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))  # sklearn.utils.Bunch 클래스 : 딕셔너리 자료형과 유사함

<class 'sklearn.utils._bunch.Bunch'>


In [10]:
# key 값 확인
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [14]:
print('\n feature_names의 type:', type(iris_data.feature_names))    # list
print(' feature_names의 shape:', len(iris_data.feature_names))      # list의 shape은 len()으로 확인
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))     # ndarray
print(' target_names의 shape:', iris_data.target_names.shape)      # (3,)
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))      # ndarray
print(' data의 shape:', iris_data.data.shape)       # (150,4)
print(iris_data.data)

print('\n target의 type:', type(iris_data.target))  # ndarray
print(' target의 shape:', iris_data.target.shape)   # (150,)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: (3,)
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]


## **Model Selection 모듈 소개**

### **학습/테스트 데이터 세트 분리 - train_test_split()**



```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= , train_size= , shuffle= , random_state= )
```

* train_test_split()의 반환값 : 튜플 형태 (train_X, test_X, train_y, test_y)
* test_size : 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할 것인지 결정, default : 0.25
* train_size : 전체 데이터에서 학습용 데이터 세트 크기를 결정, 잘 사용되지 않음(test_size를 결정하면 자동적으로 결정되기 때문)
* shuffle : 데이터를 분리하기 전에 데이터를 미리 섞을지 결정, default : True
* random_state : 호출할 때마다 동일한 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값, 이를 지정하지 않으면 수행할 때마다 다른 학습/테스트 용 데이터를 생성함 (seed와 유사)



In [15]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

#학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0


In [16]:
# test_size = 0.3으로 iris_data 분리

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [17]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


### **교차 검증**

* 학습/테스트 데이터 세트를 분리하여 예측을 수행하는 방법은 Overfitting에 취약하다는 약점을 가질 수 있음
* 과적합(Overfitting) : 모델이 학습 데이터에만 과도하게 최적화되어 실제 예측을 다른 데이터로 수행할 경우 예측 성능이 과도하게 떨어지는 것
* 고정된 학습 데이터와 테스트 데이터로 평가를 하다 보면 해당 테스트 데이터에만 과적합되는 모델이 만들어지고, 다른 테스트 데이터가 들어올 경우 성능이 저하됨
* 이 문제점을 개선하기 위해 '교차 검증'을 이용
* ML에 사용되는 데이터 세트를 학습, 검증, 테스트 데이터 세트로 나눔


#### **K-Fold 교차 검증**

* 가장 보편적으로 사용되는 교차 검증 기법
* K개의 데이터 폴드 세트를 만들어 K번 만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행하는 방법

![K-Fold](https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyNDA2MjRfMTkg%2FMDAxNzE5MjEyMzcxMTMz.WXCfAznfWgj8FSDoAVor-U9qdEsAR3TqwodS9LM7Ql0g.oG3Lf3AxqCyBiPh7S7LrHObUJwQKMDCSX9idHtcXldUg.PNG%2Fimage.png&type=sc960_832)

In [18]:
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [19]:
n_iter = 0

# KFold 객체의 split()을 호출하면 폴드별 학습용, 검증용 테스트의 row index를 array로 반환
for train_index, test_index in kfold.split(features):

    # kfold.split() : 학습/검증용 데이터로 분할할 수 있는 "인덱스" 반환
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    #반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))

    cv_accuracy.append(accuracy)

# 개별 iterationq별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기:30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도:0.9667, 학습 데이터 크기:120, 검증 데이터 크기:30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도:0.8667, 학습 데이터 크기:120, 검증 데이터 크기:30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도:0.9333, 학습 데이터 크기:120, 검증 데이터 크기:30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도:0.7333, 학습 데이터 크기:120, 검증 데이터 크기:30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


#### **Stratified K-Fold**

* 불균형한 분포도를 가진 레이블 데이터 집합을 위한 K-Fold 방식
    * 특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한쪽으로 치우치는 집합
* K-Fold가 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습/테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결함
* 원본 데이터의 레이블 분포를 먼저 고려한 후 이 분포와 동일하게 학습/검증 데이터 세트를 분배함

In [20]:
# K-Fold의 문제점 확인

import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [21]:
kfold = KFold(n_splits=2)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter +=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차검증 : 1
학습 레이블 데이터 분포:
 label
2    50
1    25
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
1    25
Name: count, dtype: int64
## 교차검증 : 2
학습 레이블 데이터 분포:
 label
0    50
1    25
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
1    25
Name: count, dtype: int64


첫 번째 교차 검증 : 학습 레이블에 1,2밖에 없음 -> 0은 모두 검증데이터 세트에 있고 절대 예측 못 함

In [22]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64


학습 레이블과 검증 레이블 데이터 값의 분포도가 거의 동일하게 할당되었음

이렇게 분할이 되어야 레이블 값 0,1,2 를 모두 학습할 수 있고, 이를 기반으로 검증을 수행할 수 있음

In [24]:
df_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# skfold의 split() 호출 시 반드시 피처, 레이블 데이터 세트가 모두 있어야 함 (kfold : 피처만)
for train_index, test_index in skfold.split(features, label):
    # split()으로 반환한 인덱스를 이용해 학습/검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    # 반복 시마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도', np.round(np.mean(cv_accuracy),4))


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도 0.9667


#### **cross_val_score()**



```
#estimator, X, y, scoring, cv 가 주요 파라미터
cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs)
```

* cross_val_score() 반환 값 : scoring 으로 지정된 성능 지표 측정값
* estimator : Classifier / Regressor
    * classifier로 입력된 경우 Stratified K-Fold 방식으로 분할
    * regressor의 경우 skfold가 불가능하므로 K-Fold 방식으로 분할
* X : feature dataset
* y : label dataset
* scoring : 예측 성능 평가 지표
* cv : 교차 검증 폴드 수



In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# scoring = accuracy, 교차 검증 세트(cv)는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


### **GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에**

In [26]:
grid_parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [27]:
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

# 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [28]:
# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
# refit : True가 default, True이면 가장 좋은 파라미터 설정으로 재학습시킴

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출하여 df로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [29]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [30]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667


일반적으로 학습 데이터를 GridSearchCV를 이용해 최적 하이퍼 파라미터 튜닝을 수행한 뒤에 별도의 테스트 세트에서 이를 평가함으로써 머신러닝 모델에 적용함