<a href="https://colab.research.google.com/github/wheemin-2/24-2-ESAA/blob/main/ESAA_YB_1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_%EB%AC%B8%EC%A0%9C_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print('numpy version:',np.version.version)
print(np.show_config())

numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array3 = np.zeros(10)
print(array3)
print(array3.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# array의 memory size : (원소의 수) * (하나의 원소의 메모리 사이즈)
# numpy 에 내장된 함수 nbytes를 이용
# array3으로 확인
print('Size of an array3:', array3.size)
print('Size of one array element in bytes:', array3.itemsize)
print('Size of the memory size of array3:', array3.size*array3.itemsize)
print(array3.nbytes)

Size of an array3: 10
Size of one array element in bytes: 8
Size of the memory size of array3: 80
80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array1 = np.zeros(10)
array1[4] = 1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array6 = np.arange(start=10,stop=50)
print(array6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array6_desc = np.sort(array6)[::-1]
print(array6_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array8 = np.arange(9).reshape(3,3)
print(array8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array9 = np.array([1,2,0,0,4,0])
np.where(array9!=0)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array11 = np.array(np.random.random(27))
print(array11)
print()

print('3x3x3 array:\n',array11.reshape(3,3,3))

[0.09650344 0.92168871 0.39177512 0.21772691 0.48258486 0.7256239
 0.15904805 0.7258888  0.13625659 0.79643659 0.36125215 0.48293081
 0.88680574 0.82438461 0.89960938 0.49919069 0.22848047 0.07136638
 0.359828   0.34659277 0.67146964 0.8103228  0.03115647 0.56614718
 0.10402818 0.76656834 0.6379494 ]

3x3x3 array:
 [[[0.09650344 0.92168871 0.39177512]
  [0.21772691 0.48258486 0.7256239 ]
  [0.15904805 0.7258888  0.13625659]]

 [[0.79643659 0.36125215 0.48293081]
  [0.88680574 0.82438461 0.89960938]
  [0.49919069 0.22848047 0.07136638]]

 [[0.359828   0.34659277 0.67146964]
  [0.8103228  0.03115647 0.56614718]
  [0.10402818 0.76656834 0.6379494 ]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array12 = np.array(np.random.random(100)).reshape(10,10)
print(array12)
print()
print('array12의 최솟값은 {0}이고, 최댓값은 {1}이다'.format(np.min(array12), np.max(array12)))

[[0.71255967 0.31962751 0.49274917 0.70176708 0.50165059 0.01019184
  0.00919194 0.24350603 0.38680372 0.03392309]
 [0.05421317 0.1470029  0.49201985 0.48860154 0.73847303 0.40701533
  0.91658864 0.7631551  0.32448599 0.05134235]
 [0.7188088  0.21526333 0.67276694 0.09767411 0.01195822 0.09374939
  0.68799687 0.1513886  0.8741962  0.39666067]
 [0.4158496  0.63322    0.48066295 0.4104348  0.04387552 0.69462573
  0.7899776  0.36233452 0.36723927 0.07694953]
 [0.66222454 0.29164147 0.84866171 0.60677277 0.52392956 0.53156845
  0.59888995 0.67239697 0.13324905 0.69892109]
 [0.46046292 0.87285946 0.29665404 0.67925037 0.17320685 0.1217356
  0.85106808 0.7076505  0.99499024 0.60230911]
 [0.81925506 0.90487146 0.78394436 0.82271501 0.26883086 0.04015902
  0.83055231 0.93827882 0.75939287 0.46915338]
 [0.35614787 0.26786419 0.66333726 0.11264132 0.79844806 0.7226263
  0.2937573  0.8624758  0.00461532 0.94166353]
 [0.40618963 0.12657344 0.18403085 0.07309502 0.57216772 0.36754217
  0.49236457 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array13 = np.random.random(30)
np.mean(array13)

0.5405232417041603

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
# 10x10 array

n=10
array14 = np.zeros((10,10))
array14[[0,n-1],:] = 1
array14[:,[0,n-1]] = 1
print(array14)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
a = np.arange(1,5)
array16 = np.diag(a,k=-1)
print(array16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
help(np.tile)

Help on _ArrayFunctionDispatcher in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetit

In [ ]:
array17 = np.array([[0,1],
                    [1,0]])
print(np.tile(array17,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array19 = np.array(np.random.random(25)).reshape(5,5)
a_mean = np.mean(array19)
a_sd = np.std(array19)
n_array19 = (array19 - a_mean)/a_sd
print(n_array19)
print('정규화된 array 평균 확인:', np.mean(n_array19))
print('정규화된 array 표준편차 확인:', np.std(n_array19))

[[-1.39113089  1.0612916  -0.82834866 -1.05540113  0.57198918]
 [ 0.34127894 -0.20029933 -1.09323718 -0.42599181  1.48521721]
 [ 0.85236621  0.24518625 -1.36141041 -0.97782853  1.2988131 ]
 [ 1.36159633  1.53363778 -0.7757829  -0.94126847  1.45920874]
 [ 0.74933249 -0.63925069 -0.60219967 -1.1735621   0.50579394]]
정규화된 array 평균 확인: -2.5313084961453567e-16
정규화된 array 표준편차 확인: 1.0


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
RGBA = np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
print(RGBA)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array21_a = np.arange(15).reshape(5,3)
array21_b = np.arange(6).reshape(3,2)
print(np.dot(array21_a, array21_b))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [71]:
array22 = np.arange(10)
#방법1 : np.negative 함수 사용
array22[3:9] = np.negative(array22[3:9])
print(array22)

#방법2
array22 = np.arange(10)
array22[3:9] *= -1
print(array22)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# sum
print(sum(range(5),-1))  # 0+1+2+3+4+(-1)

# np.sum
from numpy import *
print(sum(range(5),-1))  # axis=-1에 대하여 range(5)를 더해라

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

**비트 시프트 연산 <<,>>**

* 정수를 2배로 곱하거나 나누어 계산해 주는 비트단위시프트연산자 <<, >>를 이용할 수 있다.

* 컴퓨터 내부에는 2진수 형태로 값들이 저장되기 때문에,
2진수 형태로 저장되어 있는 값들을 왼쪽(<<)이나 오른쪽(>>)으로
지정한 비트 수만큼 밀어주면 2배씩 늘어나거나 1/2로 줄어듦

* 왼쪽 비트시프트(<<)가 될 때에는 오른쪽에 0이 주어진 개수만큼 추가
* 오른쪽 비트시프트(>>)가 될 때에는 왼쪽에 0(0 또는 양의 정수인 경우)이나 1(음의 정수인 경우)이 개수만큼 추가되고 가장 오른쪽에 있는 1비트는 사라짐



```
n = 10       #2진수 : 1010
print(n<<1)  #10을 2배 한 값인 20 이 출력된다. (10100)
print(n>>1)  #10을 반으로 나눈 값인 5 가 출력된다. (0101)
print(n<<2)  #10을 4배 한 값인 40 이 출력된다. (101000)
print(n>>2)  #10을 반으로 나눈 후 다시 반으로 나눈 값인 2 가 출력된다. (0010)

```



In [ ]:
z = np.arange(3)
print(z**z)     # 각 원소를 제곱
print(2<<z>>2)  # 4배 했다가 1/4배
print(z <- z)   # illegal. python에서는 할당을 화살표로 하지 않음
print(1j*z)     # complex(2,3) = 2+3j
print(z/1/1)
print(z<z>z)    # 오류

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-18-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-18-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-18-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2)
Z1[Z1 == Z2]  # 위치까지 같아야 True..

[1 3 4 8 0 2 5 6 7 5] [9 2 0 5 0 8 9 1 3 2]


array([0])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)  # nan vs. 1j

<ipython-input-19-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [41]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
import datetime

In [ ]:
start = np.datetime64(datetime.date(2016,7,1))
end = np.datetime64(datetime.date(2016,8,1))
July = np.arange(start,end,dtype='datetime64[D]')
print(July)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [50]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)       # out을 B로 하여 B자체를 [3,3,3]으로 바꿈
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[-0.5 -0.5 -0.5] [3. 3. 3.]


array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [52]:
array30 = np.array(np.random.random(5)*10)
print(array30)

#방법 1 : % (결과값이 나머지)
remain = array30 % 1
print(array30 - remain)

#방법 2 : // (결과값이 몫)
q = array30 // 1
print(q)

[1.28493012 1.67785314 9.80926723 6.19284359 9.98279063]
[1. 1. 9. 6. 9.]
[1. 1. 9. 6. 9.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
# np.random.random : 0~1 사이의 실수를 임의로 추출
# 0~4의 범위를 만들기 위해 뽑힌 실수에 4를 곱함
array31 = np.array(np.random.random(25)*4)
array31 = array31.reshape(5,5)
print(array31)

# 0~4 범위를 만족하는지 확인
print(np.min(array31),np.max(array31))

[[1.23060219 0.64135638 0.24978603 0.31174424 1.74731018]
 [3.80561393 2.06156837 3.05748827 1.72932224 2.65712433]
 [0.51074813 1.82715148 0.57285983 1.72174843 2.33068527]
 [0.41153532 0.40367913 2.76706418 2.90705693 0.29923774]
 [3.94924472 2.94705727 0.04528473 2.4491356  2.26683685]]
0.04528473389130072 3.9492447243422943


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [57]:
array32 = np.array(np.random.random(10))
np.sort(array32)

array([0.20111597, 0.30013842, 0.428906  , 0.55093049, 0.55216932,
       0.63707186, 0.64678308, 0.80122882, 0.82528516, 0.97520874])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [61]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)

equal = np.array_equal(A,B)
print(equal)

[0 1 1 1 1] [0 0 0 0 0]
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
데카르트 좌표계 (x,y) -> 극좌표계 (r, theta)

Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [62]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)    # arctan2 (y좌표, x좌표)
print(R)
print(T)

[0.76616838 0.78937971 0.92630009 0.90510282 1.34597222 0.93314866
 0.51528288 0.48848529 1.01101413 0.50777114]
[0.30717973 1.1655787  0.538919   0.82079514 0.74492503 0.60795791
 0.92197717 1.45588944 0.38074417 1.06314532]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.array(np.random.random(10))
Z[Z.argmax()]=0
print(Z)

[0.64117181 0.         0.05515196 0.58674721 0.72217564 0.96336566
 0.39284285 0.57029548 0.457896   0.31494366]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
Z[np.abs(Z-v).argmin()]

32

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [63]:
Z = np.arange(9).reshape(3,3)
for index, z in np.ndenumerate(Z):
    print(index,z)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [64]:
n = 10
p = 4
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),10)
print(Z)

[[ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [66]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[3 8 0]
 [1 7 8]
 [7 6 4]]


In [68]:
# column 1
print(Z[:,0].argsort())
print(Z[Z[:,0].argsort()])

[1 0 2]
[[1 7 8]
 [3 8 0]
 [7 6 4]]


In [69]:
# column2
c2_index = Z[:,1].argsort()
print(c2_index)
print(Z[c2_index])

[2 1 0]
[[7 6 4]
 [1 7 8]
 [3 8 0]]


In [70]:
# column 3
c3_index = Z[:,2].argsort()
print(c3_index)
print(Z[c3_index])

[0 2 1]
[[3 8 0]
 [7 6 4]
 [1 7 8]]
