# **넘파이(Numpy)**



In [1]:
import numpy as np

## **ndarray**

* 넘파이의 기반 데이터 타입 : ndarray
* ndarray를 이용하여 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행을 할 수 있음
* 넘파이 ndarray 배열의 차원
![ndarray 차원](https://search.pstatic.net/sunny/?src=https%3A%2F%2Fvelog.velcdn.com%2Fimages%2Fgangjoo%2Fpost%2F3b66a81b-af58-4be4-a380-7973866169d8%2Fimage.png&type=sc960_832)

## **array 함수**

* array() : list와 같은 인자 -> ndarray로 변환
    * shape : ndarray의 크기를 튜플 형태로 가짐
    * ndim : ndarray의 차원을 확인


In [2]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array1 형태:', array1.shape) # (3,)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array1 type:',type(array2))
print('array1 array1 형태:', array2.shape)  # (2,3)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3.shape)  # (1,3)

array1 type: <class 'numpy.ndarray'>
array1 array1 형태: (3,)
array1 type: <class 'numpy.ndarray'>
array1 array1 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


## **ndarray의 데이터 타입**

* ndarray내의 데이터값 : 숫자, 문자열, 불 값 등 모두 가능
* 숫자형 : int, unsigned int, float, complex 타입
* int, unsigned int : ~ 32 bit
* float : ~ 128 bit
* complex : int와 float보다 더 큰 숫자값이나 정밀도를 위해 존재

* ***한 개의 ndarray 객체에는 한 개의 데이터 타입만 존재!!*** > (list와 차이)
* dtpye으로 확인 가능

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


* 다른 데이터 유형이 섞여있는 list를 ndarray로 변환하는 경우

* 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용!

* int < float < string

In [5]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


* astype() : ndarray 내 데이터 타입 변경
    * 대용량 데이터 저장 시 메모리 절약에 이용됨
    * *ex) int로 충분한데 float으로 저장되어있는 경우*
    * float > int 변환 시 소수점 버림

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

* arange() : 0부터 n-1까지의 값을 순차적으로 ndarrray 데이터값으로 변환
* zeros(), ones() : 튜플 형태의 shape값을 입력, dtype 지정 가능(default : float64)



In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # int, (10,)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)  # default dtype : float

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## **ndarray의 차원과 크기를 변경하는 reshape()**

* 변환을 원하는 크기를 함수 인자로 부여
* 행방향으로 reshape
* 인자로 -1을 넣으면 알아서 reshape 해줌


In [9]:
array1 = np.arange(10)  # 0~9까지의 1차원 array 생성 (10,)
print('array1:\n', array1)
print()

array2 = array1.reshape(2,5)
print('array2:\n', array2)
print()

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# 오류
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
array1 = np.arange(10)
print(array1)
print()

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
print()

array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]

array2 shape: (2, 5)

array3 shape: (5, 2)


In [ ]:
# 오류
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

* **reshape(-1,1)**

    * 원본 ndarray가 어떤 형태든 2차원에 column이 1개인 ndarray로 변환됨을 보장
    * stack, concat으로 결합할 때 유용


In [12]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())


# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:\n', array5.shape)


# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:\n', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:
 (8, 1)


## **넘파이의 ndarray의 데이터 세트 선택하기 - indexing**

* 특정 데이터만 추출 : 원하는 위치의 인덱스 값 지정

* Slicing : 연속된 인덱스상의 ndarray를 추출하는 방식
    * a:b > a부터 b-1까지 추출

* Fancy Indexing : 일정한 인덱싱 집합을 list/ndarray 형태로 지정하여 해당 위치에 있는 데이터의 ndarray를 반환

* Boolean Indexing : 특정 조건에 해당하는(True) 인덱스 위치에 있는 데이터의 ndarray를 반환

### 단일값 추출
* 인덱스에 '-' 기호를 이용하면 뒤에서부터 데이터 추출이 가능

In [13]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]  # 인덱스는 0부터 시작함에 유의, 3
print('value:',value)
print(type(value)) # int


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [14]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


* 단일 인덱스를 이용한 ndarray 내의 데이터값 수정 가능

In [15]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


### 다차원 ndarray에서 단일값 추출

In [16]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2]) # 인덱스는 0부터 시작함에 유의

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### Slicing

In [17]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]  # 0~2까지 slicing
print(array3)  # [1,2,3]
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [18]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### 다차원 ndarray에서 slicing

In [19]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2,0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3,0:3])
print('array2d[1:3, :]\n', array2d[1:3,:])
print('array2d[:, :]\n', array2d[:,:])
print('array2d[:2, 1:]\n', array2d[:2,1:])
print('array2d[:2, 0]\n', array2d[:2,0])   # shape (2,)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


* 2차원 ndarray에서 뒤에 오는 index를 없애면 row축(axis 0)을 기준으로 slicing한다.

In [20]:
print(array2d[0])
print(array2d[1])  # index1인 row를 반환
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### Fancy Indexing

* list나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱

In [21]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### **Boolean Indexing**

* 조건 필터링과 검색을 동시에 할 수 있음

* [] 내에 조건문을 그대로 기재하여 사용

In [22]:
array1d = np.arange(1,10)
# [  ] 안에 array1d > 5 Boolean indexing을 적용

array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [23]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

불린 인덱싱 원리 : [   ] 안에 들어가는 조건을 참으로 만드는 위치에 있는 데이터를 반환

* Step1. ndarray의 필터링 조건을 [] 안에 기재
* Step2. False 값은 무시하고 True 값에 해당하는 "인덱스값"만 저장
    * 이때 True 값 자체인 1을 저장하는 것이 아님. 인덱스를 저장함
* Step3. 저장된 인덱스 데이터 세트로 ndarray 조회

In [24]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [25]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


## **행렬의 정렬 - sort(), argsort()**

### **np.sort(), ndarray.sort()**
* np.sort() : 넘파이에서 sort를 호출, 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환

* ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None

In [27]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort로 정렬
sort_array1 = np.sort(org_array)
print('np.sort(  ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort(  ) 호출 후 원본 행렬', org_array)

# ndarray.sort로 정렬
sort_array2 = org_array.sort()
print('org_array.sort(  ) 호출 후 반환된 행렬:', sort_array2)  # None
print('org_array.sort(  ) 호출 후 원본 행렬:', org_array)      # 원본 행렬 바뀜

원본 행렬: [3 1 9 5]
np.sort(  ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort(  ) 호출 후 원본 행렬 [3 1 9 5]
org_array.sort(  ) 호출 후 반환된 행렬: None
org_array.sort(  ) 호출 후 원본 행렬: [1 3 5 9]


* 정렬 디폴트는 오름차순
* 내림차순은 [::-1]을 적용

In [29]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


### **다차원 ndarray에서 정렬**

* axis 축 값 설정으로 통해 row/column 방향으로 정렬 수행이 가능

In [30]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### **argsort()**

* 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 사용

* np.argsort() : 정렬 행렬의 *원본 행렬 인덱스*를 ndarray형으로 반환

In [31]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


* 내림차순 정렬 시 np.argsort()[::-1]

In [32]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)


행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [35]:
# argsort 활용 예시

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

# 성적이 낮은 순으로 학생 이름을 출력하고 싶은 경우

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## **행렬 내적, 전치행렬**

### **행렬 내적(행렬 곱) - np.dot()**

In [36]:
A = np.array([[1,2,3],
              [4,5,6]])    # 2x3 mtx

B = np.array([[7,8],
              [9,10],
              [11,12]])   # 3x2 mtx

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)  # 2x2 mtx

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### **전치 행렬 - np.transpose()**

In [37]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
